//
val df = sqlContext.read.format("csv").load("/home/mywh/data/resultData/215Card/215Card_2017/215Card_201702/215Card_20170201.csv")
//
nameColumn = ["ID", "CTYPE" , "STDNO", "PNO", "UNT",
              "LDATE,TDATE,QTY,STRNO,TNO,MRK3,MRK4,MRK5,TICKETNO,SHIP,CARNO,PNAME,TICKETTYPE,CUSAUNT,CUSMUNT,TTIME,CARDMNO,CTYPEMK,MILE,PRICE,CNO,BILLNO,ATYPE,ADATE,RDATE,MDATE,SID,YYMM,BPRICE,SPRICE,MK1,MK2,MK3,S3_SEQNO,ISLAND_NO,GUN_NO,EDC_VERSION
